### ISSUE TITLE
How to get correct real world dimensions ?

### ISSUE THREAD

**Issue by JuhaW** [stuffmatic/fSpy-Blender#17]
Badminton court dimensions are 6.10 x 13.41m and every time I set Reference distance for x correct (6.1) then the plane is too long (length) and when I set Reference distance for y (13.41) then the plane is too narrow.
Fspy export file and image are included.

http://puu.sh/E8CbJ/17fd60b756.png
[Export.zip](https://github.com/stuffmatic/fSpy-Blender/files/3541550/Export.zip)

**Comment by stuffmatic** [comment]
I'm guessing the x axis vanishing point can't be reliably computed because the lines parallel to the x axis are (near) parallel. 

From the ["Basics" section of the fSpy site](https://fspy.io/basics/):

_When the line segements are near-parallel, the vanishing point position cannot be computed accurately. The larger the angle between the line segments, the better._

**Comment by JuhaW** [comment]
Ok, I thought this would be the easiest scenario of perspective. Any tips ?

**Comment by stuffmatic** [comment]
The problem with your image seems to be that there is only one vanishing point that can be computed with sufficient accuracy. If there's only one vanishing point, you'll need to manually specify the focal length. If you don't have the actual value, you might be able to find a good enough value by trial and error. See _Using images with a single vanishing point_ in [the tutorial on the fSpy site](https://fspy.io/tutorial/) for more info.

**Comment by JuhaW** [comment]
Thank you, that solved the problem !
http://puu.sh/E9K0O/3037b06010.png
